// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmWuyROQqt-fH6tSdbgATWoxNPu6HvgCo',
    appId: '1:368128411900:web:fa6de6fbfc6bf867b7ef79',
    messagingSenderId: '368128411900',
    projectId: 'mbmctrial-app',
    authDomain: 'mbmctrial-app.firebaseapp.com',
    storageBucket: 'mbmctrial-app.firebasestorage.app',
    measurementId: 'G-5P4N007TQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARA2nz6l3R1J3vwP2R-b9FXzpb52J9bt8',
    appId: '1:368128411900:android:689e597450f38e3fb7ef79',
    messagingSenderId: '368128411900',
    projectId: 'mbmctrial-app',
    storageBucket: 'mbmctrial-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiierc8wS5WL4Tphl_VZ-lOstREcsmwVE',
    appId: '1:368128411900:ios:2d487d6fbcbd0fadb7ef79',
    messagingSenderId: '368128411900',
    projectId: 'mbmctrial-app',
    storageBucket: 'mbmctrial-app.firebasestorage.app',
    iosBundleId: 'com.example.mbmc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiierc8wS5WL4Tphl_VZ-lOstREcsmwVE',
    appId: '1:368128411900:ios:2d487d6fbcbd0fadb7ef79',
    messagingSenderId: '368128411900',
    projectId: 'mbmctrial-app',
    storageBucket: 'mbmctrial-app.firebasestorage.app',
    iosBundleId: 'com.example.mbmc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmWuyROQqt-fH6tSdbgATWoxNPu6HvgCo',
    appId: '1:368128411900:web:e0b5965dbc788f1fb7ef79',
    messagingSenderId: '368128411900',
    projectId: 'mbmctrial-app',
    authDomain: 'mbmctrial-app.firebaseapp.com',
    storageBucket: 'mbmctrial-app.firebasestorage.app',
    measurementId: 'G-P4PKVBRHDF',
  );
}
